package SimpArcModTestArtifacts;

import java.awt.Dimension;
import java.awt.Point;

import GenCol.entity;
import view.modeling.ViewableAtomic;
import view.modeling.ViewableComponent;
import view.modeling.ViewableDigraph;

public class Fake_gpt2 extends ViewableDigraph
{
    public Fake_gpt2()
    {
        super("gpt2");

        ViewableAtomic g = new Fake_genr("Fake_g", 10);
        ViewableAtomic p = new Fake_proc("Fake_p", 5);
        ViewableAtomic p2 = new Fake_proc2("Fake_p2", 100);
        ViewableAtomic t = new Fake_transd("Fake_t", 300);

        add(g);
        add(p);
        add(p2);
        add(t);

        addInport("in");
        addInport("start");
        addInport("stop");
        addOutport("out");
        addOutport("result");

        addTestInput("start", new entity());
        addTestInput("stop", new entity(), 5.0);

        addCoupling(this, "in", g, "in");

        addCoupling(this, "start", g, "start");
        addCoupling(this, "stop", g, "stop");

        addCoupling(g, "out", p, "in");
        addCoupling(g, "out", p2, "in");

        addCoupling(g, "out", t, "ariv");
        addCoupling(p, "out", t, "solved");
        addCoupling(p2, "out", t, "solved");
        addCoupling(t, "out", g, "stop");

        addCoupling(p, "out", this, "out");
        addCoupling(p2, "out", this, "out");
        addCoupling(t, "out", this, "result");
    }

    /**
     * Automatically generated by the SimView program. Do not edit this
     * manually, as such changes will get overwritten.
     */
    public void layoutForSimView()
    {
        preferredSize = new Dimension(591, 269);
        ((ViewableComponent) withName("p2")).setPreferredLocation(new Point(22, 22));
        ((ViewableComponent) withName("g")).setPreferredLocation(new Point(113, 82));
        ((ViewableComponent) withName("t")).setPreferredLocation(new Point(-10, 180));
        ((ViewableComponent) withName("p")).setPreferredLocation(new Point(233, 196));
    }
}
