package CellularAutomata.FF_Rothermel;

import GenCol.Pair;
import model.modeling.CAModels.TwoDimCellSpace;

public class EnvironmentCellTest extends TwoDimCellSpace {

    public EnvironmentCellTest() {
        this(100, 100);
    }

    public EnvironmentCellTest(int xDim, int yDim) {
        super("moor", xDim, yDim);
        this.numCells = xDim * yDim;
        CellUtils.init(2, 2);
        for (int i = 0; i < xDimCellspace; i++) {
            for (int j = 0; j < yDimCellspace; j++) {
                EnvironmentCell cell = new EnvironmentCell(i, j);
                addCell(cell);
                if (i == 49 && j == 49){
                    cell.setStartFire(true);
                }
            }
        }
        doNeighborToNeighborCoupling();
    }

    /**
     * Automatically generated by the SimView program.
     * Do not edit this manually, as such changes will get overwritten.
     */
    @Override
    public void layoutForSimView() {
    }
}
